
[package]
name = "disasm"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
addr2line = "0.5.0"
capstone = "0.2.0"
failure = "0.1.1"
goblin = "0.0.13"
object = "0.6.0"
